#NumPy & Pandas Coding Assignment

In [1]:
#importing required libraries
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

##Q1. Employee Salary Adjustment
A company stores salaries in a NumPy array.
<br>salaries = np.array([45000, 52000, 61000, 48000, 75000])

###1. Increase all salaries by 10%.

In [2]:
salaries=np.array([45000, 52000, 61000, 48000, 75000])
updated_salaries=salaries*1.1
updated_salaries

array([49500., 57200., 67100., 52800., 82500.])

###2. Find the average salary.

In [3]:
avg_salary=salaries.mean()
print("Average salary: ",avg_salary)

Average salary:  56200.0

###3.Find the maximum and minimum salary.

In [4]:
max_salary=salaries.max()
min_salary=salaries.min()
print("Maximum salary: ",round(max_salary,2))
print("Minimum salary: ",round(min_salary,2))

Maximum salary:  75000
Minimum salary:  45000

###4.Print salaries greater than 60000.

In [5]:
high_salaries=salaries[salaries>60000]
high_salaries

array([61000, 75000])

##Q2. Sales Data Analysis
Daily sales of a store for 10 days:
<br>sales = np.array([120,150,180,200,170,160,210,220,190,175])

###1. Compute total sales.

In [6]:
sales = np.array([120,150,180,200,170,160,210,220,190,175])
total_sales=sales.sum()
print("Total sales: ",total_sales)

Total sales:  1775

###2. Compute mean and standard deviation.

In [7]:
avg_sales=sales.mean()
sales_std_deviation=sales.std()
print("Average sales: ",avg_sales)
print("Standard deviation of salaries: ",round(sales_std_deviation,2))

Average sales:  177.5
Standard deviation of salaries:  28.22

###3. Identify days where sales exceeded the average.

In [8]:
high_sales=sales[sales>avg_sales]
high_sales

array([180, 200, 210, 220, 190])

###4. Normalize the sales using Min-Max scaling.
normalized = (x-min)/(max-min)

In [9]:
normalized_sales = (sales-sales.min())/(sales.max()-sales.min())
normalized_sales

array([0.  , 0.3 , 0.6 , 0.8 , 0.5 , 0.4 , 0.9 , 1.  , 0.7 , 0.55])

##Q3. Matrix Operations for Business Data

A company has sales data for 3 products across 4 regions.
<br>sales_matrix = np.array([
<br>[120,140,130,150],
<br>[80,90,100,95],
<br>[200,210,190,205]
])

###1. Find total sales per product.

In [10]:
sales_matrix = np.array([
[120,140,130,150],
[80,90,100,95],
[200,210,190,205] ])
sales_product=np.sum(sales_matrix,axis=1)
print("Total sales per product: ",sales_product)

Total sales per product:  [540 365 805]

###2. Find total sales per region.

In [11]:
sales_region=np.sum(sales_matrix,axis=0)
print("Total sales per region: ",sales_region)

Total sales per region:  [400 440 420 450]

###3. Identify the best performing product.

In [12]:
best_product = np.argmax(sales_product)+1  #+1 as indexing starts at zero
print("Best performing product: ",best_product)

Best performing product:  3

###4. Identify the region with highest sales.

In [13]:
best_region = np.argmax(sales_region)+1
print("Region with highest sales: ",best_region)

Region with highest sales:  4

##Q4. Employee Dataset Exploration
Create a DataFrame:
<br>data = {
<br>'Employee':['A','B','C','D','E','F'],
<br>'Department':['HR','IT','IT','Finance','HR','Finance'],
<br>'Salary':[50000,65000,70000,72000,52000,68000],
<br>'Experience':[2,5,7,6,3,4]
}

###1. Convert this dictionary into a DataFrame.

In [14]:
data = {
'Employee':['A','B','C','D','E','F'],
'Department':['HR','IT','IT','Finance','HR','Finance'],
'Salary':[50000,65000,70000,72000,52000,68000],
'Experience':[2,5,7,6,3,4] }
emp_df = pd.DataFrame(data)
emp_df

  Employee Department  Salary  Experience
0        A         HR   50000           2
1        B         IT   65000           5
2        C         IT   70000           7
3        D    Finance   72000           6
4        E         HR   52000           3
5        F    Finance   68000           4

###2. Display basic statistics of the dataset.

In [15]:
emp_df.describe()

             Salary  Experience
count      6.000000    6.000000
mean   62833.333333    4.500000
std     9474.527253    1.870829
min    50000.000000    2.000000
25%    55250.000000    3.250000
50%    66500.000000    4.500000
75%    69500.000000    5.750000
max    72000.000000    7.000000

###3. Find the average salary per department.

In [16]:
avg_salary_dept = emp_df.groupby("Department")["Salary"].mean()
avg_salary_dept

Department
Finance    70000.0
HR         51000.0
IT         67500.0
Name: Salary, dtype: float64

###4. Identify employees with experience greater than 4 years.

In [17]:
exp_emp_df=emp_df[emp_df['Experience']>4]
exp_emp_df

  Employee Department  Salary  Experience
1        B         IT   65000           5
2        C         IT   70000           7
3        D    Finance   72000           6

In [18]:
exp_emp_df['Employee']

1    B
2    C
3    D
Name: Employee, dtype: object

###5. Add a new column Bonus = 10% of salary.

In [19]:
emp_df["Bonus"] = emp_df['Salary']*0.1
emp_df

  Employee Department  Salary  Experience   Bonus
0        A         HR   50000           2  5000.0
1        B         IT   65000           5  6500.0
2        C         IT   70000           7  7000.0
3        D    Finance   72000           6  7200.0
4        E         HR   52000           3  5200.0
5        F    Finance   68000           4  6800.0

##Q5. Missing Data Handling
<br>Dataset:
<br>data = {
<br>'Name':['John','Anna','Peter','Linda','David'],
<br>'Age':[28, np.nan, 35, 32, np.nan],
<br>'Salary':[50000,54000,np.nan,58000,60000]
}

###1. Detect missing values.

In [20]:
data = {
'Name':['John','Anna','Peter','Linda','David'],
'Age':[28, np.nan, 35, 32, np.nan],
'Salary':[50000,54000,np.nan,58000,60000] }
#creating  a dataframe
emp_df = pd.DataFrame(data)
emp_df

    Name   Age   Salary
0   John  28.0  50000.0
1   Anna   NaN  54000.0
2  Peter  35.0      NaN
3  Linda  32.0  58000.0
4  David   NaN  60000.0

In [21]:
emp_df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False
4  False   True   False

In [22]:
#to find count of missing values
emp_df.isnull().sum()

Name      0
Age       2
Salary    1
dtype: int64

###2. Replace missing Age with mean age.

In [23]:
emp_df['Age'].fillna(emp_df['Age'].mean(),inplace=True)
emp_df

    Name        Age   Salary
0   John  28.000000  50000.0
1   Anna  31.666667  54000.0
2  Peter  35.000000      NaN
3  Linda  32.000000  58000.0
4  David  31.666667  60000.0

###3. Replace missing Salary with median salary.

In [24]:
emp_df['Salary'].fillna(emp_df['Salary'].median(),inplace=True)
emp_df

    Name        Age   Salary
0   John  28.000000  50000.0
1   Anna  31.666667  54000.0
2  Peter  35.000000  56000.0
3  Linda  32.000000  58000.0
4  David  31.666667  60000.0

###4. Remove rows with any remaining missing values.

In [25]:
emp_df.dropna(axis=0,inplace=True)
emp_df

    Name        Age   Salary
0   John  28.000000  50000.0
1   Anna  31.666667  54000.0
2  Peter  35.000000  56000.0
3  Linda  32.000000  58000.0
4  David  31.666667  60000.0

##Q6. Sales Performance Analysis
<br>Dataset:
<br>sales_data = {
<br>'Region':['North','South','East','West','North','South','East','West'],
<br>'Salesperson':['A','B','C','D','E','F','G','H'],
<br>'Sales':[12000,15000,13000,17000,16000,14000,15500,16500]
}

In [26]:
sales_data = {
'Region':['North','South','East','West','North','South','East','West'],
'Salesperson':['A','B','C','D','E','F','G','H'],
'Sales':[12000,15000,13000,17000,16000,14000,15500,16500] }
#creating  a dataframe
sales_df = pd.DataFrame(sales_data)
sales_df

  Region Salesperson  Sales
0  North           A  12000
1  South           B  15000
2   East           C  13000
3   West           D  17000
4  North           E  16000
5  South           F  14000
6   East           G  15500
7   West           H  16500

###1. Find total sales per region.

In [27]:
sales_df.groupby('Region')['Sales'].sum()

Region
East     28500
North    28000
South    29000
West     33500
Name: Sales, dtype: int64

###2. Identify the top salesperson.

In [28]:
top_salesperson = sales_df.loc[sales_df['Sales'].idxmax(),'Salesperson']
print("Top salesperson: ",top_salesperson)

Top salesperson:  D

###3. Compute average sales across regions.

In [29]:
sales_df.groupby('Region')['Sales'].mean()

Region
East     14250.0
North    14000.0
South    14500.0
West     16750.0
Name: Sales, dtype: float64

###4. Sort the dataset by sales descending.

In [30]:
sales_df.sort_values('Sales',ascending=False)

  Region Salesperson  Sales
3   West           D  17000
7   West           H  16500
4  North           E  16000
6   East           G  15500
1  South           B  15000
5  South           F  14000
2   East           C  13000
0  North           A  12000

##Q7. Customer Purchase Analysis
<br>Dataset:
<br>data = {
<br>'CustomerID':[101,102,103,104,105,106,107],
<br>'Age':[25,45,35,50,23,40,60],
<br>'PurchaseAmount':[250,600,400,800,150,700,900],
<br>'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai','Delhi','Chennai']
}

In [31]:
data = {
'CustomerID':[101,102,103,104,105,106,107],
'Age':[25,45,35,50,23,40,60],
'PurchaseAmount':[250,600,400,800,150,700,900],
'City':['Delhi','Mumbai','Delhi','Chennai','Mumbai','Delhi','Chennai'] }
#creating  a dataframe
customer_df = pd.DataFrame(data)
customer_df

   CustomerID  Age  PurchaseAmount     City
0         101   25             250    Delhi
1         102   45             600   Mumbai
2         103   35             400    Delhi
3         104   50             800  Chennai
4         105   23             150   Mumbai
5         106   40             700    Delhi
6         107   60             900  Chennai

###1. Find the average purchase amount by city.

In [32]:
customer_df.groupby('City')['PurchaseAmount'].mean()

City
Chennai    850.0
Delhi      450.0
Mumbai     375.0
Name: PurchaseAmount, dtype: float64

###2. Identify customers with purchase above overall average.

In [33]:
Avg_purchase= customer_df['PurchaseAmount'].mean()
above_avg_customer_df=customer_df[customer_df['PurchaseAmount']>Avg_purchase]
above_avg_customer_df

   CustomerID  Age  PurchaseAmount     City
1         102   45             600   Mumbai
3         104   50             800  Chennai
5         106   40             700    Delhi
6         107   60             900  Chennai

In [34]:
above_avg_customer_df['CustomerID']

1    102
3    104
5    106
6    107
Name: CustomerID, dtype: int64

###3. Find the city generating the highest revenue.

In [35]:
top_city_sales=customer_df.groupby('City')['PurchaseAmount'].sum()
top_city=top_city_sales.idxmax()
print("City generating highest revenue: ",top_city)

City generating highest revenue:  Chennai

###4. Create a column Age_Group:
<br><30 → Young
<br>30–50 → Adult
<br>50 → Senior

In [36]:
#defining a function for creating age_group
def age_group(age):
  if age<30:
    return 'Young'
  elif (age>=30 and age<50):
    return 'Adult'
  else:
    return 'Senior'

customer_df['Age_group']=customer_df['Age'].apply(age_group)
customer_df

   CustomerID  Age  PurchaseAmount     City Age_group
0         101   25             250    Delhi     Young
1         102   45             600   Mumbai     Adult
2         103   35             400    Delhi     Adult
3         104   50             800  Chennai    Senior
4         105   23             150   Mumbai     Young
5         106   40             700    Delhi     Adult
6         107   60             900  Chennai    Senior

###5. Find average purchase per age group.

In [37]:
customer_df.groupby('Age_group')['PurchaseAmount'].mean()

Age_group
Adult     566.666667
Senior    850.000000
Young     200.000000
Name: PurchaseAmount, dtype: float64

##Q8. Time Series Sales Analysis
<br>Generate data:
<br>dates = pd.date_range('2024-01-01', periods=12, freq='M')
<br>sales = [200,220,250,270,300,320,350,360,380,400,420,450]
<br>df = pd.DataFrame({'Date':dates,'Sales':sales})

In [38]:
dates = pd.date_range('2024-01-01', periods=12, freq='M')
sales = [200,220,250,270,300,320,350,360,380,400,420,450]
df = pd.DataFrame({'Date':dates,'Sales':sales})
df

         Date  Sales
0  2024-01-31    200
1  2024-02-29    220
2  2024-03-31    250
3  2024-04-30    270
4  2024-05-31    300
5  2024-06-30    320
6  2024-07-31    350
7  2024-08-31    360
8  2024-09-30    380
9  2024-10-31    400
10 2024-11-30    420
11 2024-12-31    450

###1. Convert Date to datetime index.

In [39]:
df.set_index('Date',inplace=True)
df

            Sales
Date
2024-01-31    200
2024-02-29    220
2024-03-31    250
2024-04-30    270
2024-05-31    300
2024-06-30    320
2024-07-31    350
2024-08-31    360
2024-09-30    380
2024-10-31    400
2024-11-30    420
2024-12-31    450

###2. Compute monthly percentage growth.

In [40]:
#group data by month and gets total sum
monthly_sales = df['Sales'].resample('M').sum()
monthly_prcntg_growth = monthly_sales.pct_change()*100
monthly_prcntg_growth

Date
2024-01-31          NaN
2024-02-29    10.000000
2024-03-31    13.636364
2024-04-30     8.000000
2024-05-31    11.111111
2024-06-30     6.666667
2024-07-31     9.375000
2024-08-31     2.857143
2024-09-30     5.555556
2024-10-31     5.263158
2024-11-30     5.000000
2024-12-31     7.142857
Freq: ME, Name: Sales, dtype: float64

###3. Calculate 3-month rolling average sales.

In [41]:
rolling_avg=df['Sales'].rolling(window=3).mean()
rolling_avg

Date
2024-01-31           NaN
2024-02-29           NaN
2024-03-31    223.333333
2024-04-30    246.666667
2024-05-31    273.333333
2024-06-30    296.666667
2024-07-31    323.333333
2024-08-31    343.333333
2024-09-30    363.333333
2024-10-31    380.000000
2024-11-30    400.000000
2024-12-31    423.333333
Name: Sales, dtype: float64

###4. Identify the month with highest growth rate.

In [42]:
Highest_growth_month = monthly_prcntg_growth.idxmax()
print('Month with highest growth rate: ',Highest_growth_month.strftime("%B"),'-',Highest_growth_month.year)

Month with highest growth rate:  March - 2024